`include "multi_project_harness/multi_project_harness.v"
`include "multi_project_harness/seven-segment-seconds/seven_segment_seconds.v"
`include "multi_project_harness/ws2812/ws2812.v"
`include "multi_project_harness/vga-clock/rtl/button_pulse.v"
`include "multi_project_harness/vga-clock/rtl/digit.v"
`include "multi_project_harness/vga-clock/rtl/VgaSyncGen.v"
`include "multi_project_harness/vga-clock/rtl/fontROM.v"
`include "multi_project_harness/vga-clock/rtl/vga_clock.v"
`include "multi_project_harness/spinet/rtl/spinet.v"
`include "multi_project_harness/freq_cnt/asic_freq.v"

